name: Update resume page 

on:
 push:
  branches:
    - main

jobs:
  update-resources:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          echo "This part is working"
          export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
          export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
          echo $ARM_SUBSCRIPTION_ID
        shell: bash

# name: hello world yaml

# on:
#   push:
#     branches:
#       - main
#   # pull_request:
#   #   branches:
#   #     - main
#   # workflow_dispatch:

# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: hello_world
#         run: echo "Hello world"
#         shell: bash

#   goodbye: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: goodbye 
#         run: echo "Goodbye"
#         shell: bash