name: Update resume page 

on:
 push:
  branches:
    - main

jobs:
  # Update resources according to changes
  update-resources:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # Initialize required environment variables
    env: 
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

    # Steps to deploy resources
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install changed-files action
      - name: Check for modified web files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: web-files

      # Install the latest version of Terraform CLI 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2 

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      # - name: Terraform Plan
      #   run: terraform plan -input=false

      # On push to "main", build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply if web files was modified
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          terraform apply -replace='azurerm_storage_blob.web-files["index.html"]' -auto-approve -input=false
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          echo "$(terraform output rg-name)"
          echo $(terraform output storage-name)
          echo $(terraform output cdn-profile-name)
          az cdn endpoint purge -g "$(terraform output rg-name)" \
                                -n "$(terraform output storage-name)" \
                                --profile-name "$(terraform output cdn-profile-name)" --content-paths "/*"
      
      # On push to "main", build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply if web files was not modified
        if: steps.changed-files.outputs.any_changed == 'false'
        run: terraform apply -auto-approve -input=false

 